### ISSUE TITLE
  Cannot specify link libraries for target "depthInpainting" which is not   built by this project.

### ISSUE THREAD

**Issue by zapaishchykova** [ZJULearning/depthInpainting#1]
Hello! I am trying to reproduce your results and after i do `cmake ..` i have the following:
`~/depthInpainting/build$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "4.3.0") 
CMake Error at CMakeLists.txt:25 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:26 (target_link_libraries):
  Cannot specify link libraries for target "depthInpainting" which is not
  built by this project.

-- Configuring incomplete, errors occurred!
See also "/home/anna/depthInpainting/build/CMakeFiles/CMakeOutput.log".
`

Do you have an idea why this is happening? Many thanks!

**Comment by Erientes** [comment]
Go to the file CMakeList.txt and change line 24 from:
`file(GLOB LRTV_SRC_FILES "*.cpp")`
to:
`file(GLOB LRTV_SRC_FILES "src/*.cpp")`

Then, you should be able to run cmake without errors.

Explanation: the original line pointed to the root directory, however, the cpp files are in ./src.
